Primer ejercicio

In [4]:
import numpy as np

TD = np.array([
    [2, 3, 0, 3, 7],
    [0, 5, 5, 0, 3],
    [5, 0, 7, 3, 3],
    [3, 1, 0, 9, 9],
    [0, 0, 7, 1, 3],
    [6, 9, 4, 6, 0]
])

total_terms = np.sum(TD)

In [5]:
P_TD = TD / total_terms

In [6]:
print(P_TD)

[[0.01923077 0.02884615 0.         0.02884615 0.06730769]
 [0.         0.04807692 0.04807692 0.         0.02884615]
 [0.04807692 0.         0.06730769 0.02884615 0.02884615]
 [0.02884615 0.00961538 0.         0.08653846 0.08653846]
 [0.         0.         0.06730769 0.00961538 0.02884615]
 [0.05769231 0.08653846 0.03846154 0.05769231 0.        ]]
