<a href="https://colab.research.google.com/github/ccjimenezm/machine_learning2024/blob/main/tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Primer ejercicio

In [ ]:
import numpy as np

TD = np.array([
    [2, 3, 0, 3, 7],
    [0, 5, 5, 0, 3],
    [5, 0, 7, 3, 3],
    [3, 1, 0, 9, 9],
    [0, 0, 7, 1, 3],
    [6, 9, 4, 6, 0]
])

total_terms = np.sum(TD)

In [ ]:
P_TD = TD / total_terms

In [ ]:
print(P_TD)

[[0.01923077 0.02884615 0.         0.02884615 0.06730769]
 [0.         0.04807692 0.04807692 0.         0.02884615]
 [0.04807692 0.         0.06730769 0.02884615 0.02884615]
 [0.02884615 0.00961538 0.         0.08653846 0.08653846]
 [0.         0.         0.06730769 0.00961538 0.02884615]
 [0.05769231 0.08653846 0.03846154 0.05769231 0.        ]]


2do punto P(T|D)

In [ ]:
sum_per_document = np.sum(TD, axis = 1)

In [ ]:
P_T_given_D = TD / sum_per_document[:, None]

In [ ]:
print(P_T_given_D)

[[0.13333333 0.2        0.         0.2        0.46666667]
 [0.         0.38461538 0.38461538 0.         0.23076923]
 [0.27777778 0.         0.38888889 0.16666667 0.16666667]
 [0.13636364 0.04545455 0.         0.40909091 0.40909091]
 [0.         0.         0.63636364 0.09090909 0.27272727]
 [0.24       0.36       0.16       0.24       0.        ]]


3 punto P(D|T)

In [ ]:
sum_per_term = np.sum(TD, axis = 0)

In [ ]:
P_D_given_T = TD / sum_per_term[None, :]

In [ ]:
print(P_D_given_T)

[[0.125      0.16666667 0.         0.13636364 0.28      ]
 [0.         0.27777778 0.2173913  0.         0.12      ]
 [0.3125     0.         0.30434783 0.13636364 0.12      ]
 [0.1875     0.05555556 0.         0.40909091 0.36      ]
 [0.         0.         0.30434783 0.04545455 0.12      ]
 [0.375      0.5        0.17391304 0.27272727 0.        ]]


4 punto Vector P(D)

In [ ]:
P_D = sum_per_document / total_terms
print(P_D)

[0.14423077 0.125      0.17307692 0.21153846 0.10576923 0.24038462]


5 punto Vector P(T)

In [ ]:
P_T = sum_per_term / total_terms
print(P_T)

[0.15384615 0.17307692 0.22115385 0.21153846 0.24038462]


*6* punto E(l)

In [ ]:
L = np.array([5,2,3,6,4,3])
probabilidad = 1 / len(L)

In [ ]:
E_L = np.sum(L * probabilidad)
print(E_L)

3.833333333333333


7 punto Var(l)

In [ ]:
var_L = np.var(L)
print(var_L)

1.8055555555555556
